version: '3.9'

services:
  backend:
    build:
      context: ./Backend
    container_name: hospital_backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    env_file:
      - ./Backend/.env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./Frontend
    container_name: hospital_frontend
    ports:
      - "5174:5174"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    depends_on:
      - backend

  postgres:
    image: postgres:16
    container_name: hospital_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: